### ISSUE TITLE
The .svgs are incorrect.

### ISSUE THREAD

**Issue by Alex313031** [ChromeDevTools/devtools-logo#6]
I don't know what the problem is, but I've encountered this issue before, and they've been able to fix it.
The .svgs display correctly in Chromium, but not in any other application. In gimp, inkscape, viewnoir, gnome image viewer, windows image viewer, and inkscape and boxy-svg on windows. Tested on multiple machines, it occurs in these applications on win 7 and 10, and debian 11 and ubuntu 22.04, so I'm sure it's not something on my end.
It just shows a full blue circle.

Could it be something to do with alpha, or a new .svg specification (as I said it only shows correctly in Chromium, and I'm using my own latest compiled version)

I use this logo in a project of mine, and really need the .svg to scale it up and down. Can you fix?

Heres a screenshot.
![Screenshot from 2022-05-09 13-42-58](https://user-images.githubusercontent.com/45863095/167476291-c6b97a42-582a-4532-9b5c-77c308402c97.png)

**Comment by Alex313031** [comment]
@mathiasbynens I'm tagging you since you made the .svg uploads.

**Comment by mathiasbynens** [comment]
The problem is the logos include varying amounts of whitespace at different sizes; it doesn’t just scale linearly. That’s why the SVGs include media queries — they are always 100% accurately rendered on the web. The SVG files are not guaranteed to be image editor-friendly (and are supposed to be edited).

You could consider using the static image versions instead: https://github.com/ChromeDevTools/devtools-logo#available-formats But keep in mind that in addition to not being scalable, they are not 100% accurate at all sizes. cc @petermllrr

**Comment by petermllrr** [comment]
Hi @Alex313031, thanks for raising that issue. @mathiasbynens and you are both right, these SVGs are intended for browser usage and contain media queries which are not correctly interpreted by design tools or image viewers. As a temporary workaround, you can get the vector files from the Figma file at `src/chrome-devtools-logo.fig`.

I'll create proper "plain" SVGs and add them here, so they are available in all design tools, not just Figma.

**Comment by Alex313031** [comment]
@petermllrr @mathiasbynens Thank you guys!

**Comment by Alex313031** [comment]
@mathiasbynens @petermllrr Btw, what I'm using the icon for is my Thorium project, a fork of Chromium, specifically the devtools logo which is used for thorium_shell > https://thorium.rocks/ https://github.com/Alex313031/Thorium and https://github.com/Alex313031/Thorium/tree/main/content_shell
